### ISSUE TITLE
"Add coin" does not recognize NANO

### ISSUE THREAD

**Issue by tk2600** [Crowley2012/MyCryptoMonitor#2]
Add coin failed to look up NANO.

I had tried manually add NANO.  Coin will be added, but refresh pulling doesn't update NANO.  BTW, NANO just jumped. :)

{
    "Name": "NANO",
    "Index": 0,
    "Bought": 1,
    "Paid": 0.0001234,
    "StartupPrice": 0,
    "Currency": "BTC"
  }

**Comment by Crowley2012** [comment]
The API I am using has not updated XRB to NANO for some reason. So if you want to add NANO to your portfolio add XRB!

**Comment by Crowley2012** [comment]
I actually just checked and it seems they added NANO to the API. You will be able to select NANO in the next release. Thanks.

**Comment by Crowley2012** [comment]
This has been added in version 1.1.6746.36358.
