### ISSUE TITLE
NANO price is way off

### ISSUE THREAD

**Issue by tk2600** [Crowley2012/MyCryptoMonitor#3]
Please see screen capture.  The app is update every 5 sec, and is compared to TradingView pulling Binance

![nano](https://user-images.githubusercontent.com/40469849/41923196-d4fdd6b4-7934-11e8-8c12-13af4f27dc78.jpg)

**Comment by Crowley2012** [comment]
The data is being pulled from the Crypto Compare API, which takes a weighted average from multiple exchanges. You can see the exchanges it is pulling data for NANO here: https://www.cryptocompare.com/coins/nano/markets/BTC

Currently, it is only getting data from 4 exchanges (I've never heard of any of them), but that is not the case for other coins. I believe they recently renamed XRB to NANO in their system so not all the exchanges are connected yet. In time the price will be more accurate as they connect more exchanges. Sorry for the inconvenience and I will revisit this issue in a few weeks to see if that is the case.

**Comment by tk2600** [comment]
Thanks for the quick update.  Kudos!

**Comment by Crowley2012** [comment]
Thanks for letting me know. I am going to close this for now. I will check back in a few weeks.
